version: "3.8"

services:
  api:
    build:
      context: ./src/api
      dockerfile: development.Dockerfile
    env_file:
      - ./src/api/.env.development
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_DEFAULT_SCHEMA: sfa
      API_PORT: ${API_PORT:-3000}
      BASE_URL: "http://localhost:${API_PORT:-3000}"
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    volumes:
      - ./src/api:/usr/src/api
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    user: root
    env_file:
      - db/sqlserver.env
      - db/sapassword.env
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/backups:/var/opt/mssql/data/backups
  s3:
      image: "minio/minio:latest"
      ports:
        - "9000:9000"
        - "9090:9090"
      environment:
        MINIO_ROOT_USER: "root"
        MINIO_ROOT_PASSWORD: "password"
      volumes:
        - "s3storage:/data/minio"
      command: minio server /data/minio --console-address ":9090"

  email:
    image: marcopas/docker-mailslurper
    ports:
      - 2500:2500
      - 8081:8080
      - 8085:8085

volumes:
  s3storage:
