version: "3.8"

services:
  api:
    build:
      context: ./src/api
      dockerfile: development.Dockerfile
    env_file:
      - ./src/api/.env.development
    environment: &environment-definition
      NODE_ENV: development
      DB_NAME: SFADB_DEV
      DB_HOST: db
      DB_USER: sa
      DB_PASS: &password-definition Testing1122
      DB_PORT: 1433
      DB_DEFAULT_SCHEMA: sfa
      API_PORT: ${API_PORT:-3000}
      BASE_URL: "http://localhost:${API_PORT:-3000}"
    tty: true
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    volumes:
      - ./src/api:/usr/src/api
    depends_on:
      db:
        condition: service_healthy

  test:
    build:
      context: ./src/api
      dockerfile: development.Dockerfile
    command: /bin/true
    env_file:
      - ./src/api/.env.development
    environment:
      <<: *environment-definition
      NODE_ENV: test
      DB_NAME: sfa_client_test
      DB_DEFAULT_SCHEMA: sfa
    tty: true
    volumes:
      - ./src/api:/usr/src/api
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: .
      dockerfile: ./db/db.Dockerfile
    ports:
      - "1433:1433"
    user: root
    environment:
      MSSQL_SA_PASSWORD: *password-definition
      ACCEPT_EULA: "Y"
    volumes:
      - ./db/bin:/usr/src/db/bin
      - ./db/initializers:/usr/src/db/initializers
      - db_data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/backups:/var/opt/mssql/data/backups
    healthcheck: # https://github.com/Microsoft/mssql-docker/issues/133
      test: "/opt/mssql-tools/bin/sqlcmd -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  s3:
      image: "minio/minio:latest"
      ports:
        - "9000:9000"
        - "9090:9090"
      environment:
        MINIO_ROOT_USER: "root"
        MINIO_ROOT_PASSWORD: "password"
      volumes:
        - "s3storage:/data/minio"
      command: minio server /data/minio --console-address ":9090"

  email:
    image: marcopas/docker-mailslurper
    ports:
      - 2500:2500
      - 8081:8080
      - 8085:8085

  # For easily generating large PlantUML diagrams
  # Not relevant to production environment.
  # Accessible at http://localhost:9999
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 9999:8080
    environment:
      PLANTUML_LIMIT_SIZE: 8192

volumes:
  db_data:
  s3storage:
