version: "3.8"

services:
  db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "1434:1433"
    user: root
    env_file: 
      - db/sqlserver.env
      - db/sapassword.env
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/backups/:/var/opt/sqlserver/backup
      - ./db/scripts:/var/opt/sqlserver/scripts

  s3:
      image: "minio/minio:latest"
      ports:
        - "9000:9000"
        - "9090:9090"
      environment:
        MINIO_ROOT_USER: "root"
        MINIO_ROOT_PASSWORD: "password"
      volumes:
        - "s3storage:/data/minio"
      command: minio server /data/minio --console-address ":9090"

  email:
    image: marcopas/docker-mailslurper
    ports:
      - 2500:2500
      - 8081:8080
      - 8085:8085

volumes:
  s3storage: